### ISSUE TITLE
Как скачать файл?

### ISSUE THREAD

**Issue by MrDimo0n** [nrokg/autotaxi#3]
Доброго времени суток, можете пожалуйста сказать,а лучше сделать видео как скачать и установить скрипт,я просто не понимаю как это сделать

**Comment by Abchxda** [comment]
Тоже уже пол часа пытаюсь разобраться как его скачать и вставить в приложение🤷‍♂️

**Comment by nrokg** [comment]
![image](https://user-images.githubusercontent.com/102890231/187723192-05db41e5-6351-4c01-b0ba-d6d0172fca1a.png)
code > download zip, достать из зипа autotaxi.py 
систему такси изменили, работать не будет (пока)
